version: '3'


services:
  equilator_api:
    build:
      dockerfile: ./openapi/Dockerfile
      context: .
    container_name: equilator_api
    restart: always
    volumes:
      - ./alembic:/src/alembic
      - ./openapi:/src/openapi
    ports:
      - 8000:8000
    env_file:
      - ./.env.example
    environment:
      # Env variables have default values, and there is no need to pass them all.
      # The following are the ones that are recommended to transmit:
      API_VERSION: ${API_VERSION:-Equilator API}
      API_KEY: ${API_KEY:-secret}
      DATABASE_URL: ${DATABASE_URL:-postgresql+asyncpg://root:root@equilator_api_db:5432/eq_db}
      SQL_ENGINE_ECHO: ${SQL_ENGINE_ECHO:-0}
      MONITORING_ENABLED: ${MONITORING_ENABLED:-False}
      SENTRY_DSN: ${SENTRY_DSN:-https://sentry_link}
    depends_on:
      equilator_api_db:
        condition:
          service_healthy
    logging:
      options:
        max-size: "10m"
        max-file: "5"

  equilator_api_db:
    image: postgres:14.2
    container_name: eq_db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
      POSTGRES_DB: eq_db
    healthcheck:
      test: pg_isready -U root -d eq_db
      interval: 2s
      timeout: 3s
      retries: 5
    logging:
      options:
        max-size: "10m"
        max-file: "5"
