version: '3'


services:
  equilator_api:
    image: equilator_api
    build:
      dockerfile: ./openapi/Dockerfile
      context: .
    command: sh -c "coverage run --rcfile=.coveragerc -m pytest -s openapi -vv &&
                      coverage report --precision=2 --sort=cover --skip-empty --show-missing"
    restart: always
    volumes:
      - ./alembic:/src/alembic
      - ./openapi:/src/openapi
    ports:
      - 8000:8000
    env_file:
      - ./.env.example
    depends_on:
      equilator_api_db:
        condition:
          service_healthy
    logging:
      options:
        max-size: "10m"
        max-file: "5"

  equilator_api_db:
    image: postgres:latest
    container_name: eq_db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
      POSTGRES_DB: eq_db
    # if necessary, volumes can be enabled by:
    # volumes:
    #   - /var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U root -d eq_db
      interval: 2s
      timeout: 3s
      retries: 5
    logging:
      options:
        max-size: "10m"
        max-file: "5"

# if necessary, volumes can be enabled by:
# volumes:
  # pgdata:
