"""init

Revision ID: 515ba38d7da7
Revises:
Create Date: 2022-10-23 19:44:15.341408

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = '515ba38d7da7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'designations',
        sa.Column('id', sa.String(length=500), nullable=False),
        sa.Column('range_definition', sa.String(length=5000), nullable=False),
        sa.Column('range_length', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('range_definition'),
        schema='public'
    )
    op.create_table(
        'ranges',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=500), nullable=False),
        sa.Column('hash', sa.String(length=1000), nullable=False),
        sa.Column(
            'definition',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id'),
        sa.UniqueConstraint('name'),
        schema='public'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ranges', schema='public')
    op.drop_table('designations', schema='public')
    # ### end Alembic commands ###
