name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, reopened, edited, synchronize]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r openapi/requirements.txt

    - name: Run tests
      run: |
        docker-compose -f docker-compose.test.yml up --exit-code-from equilator_api_test